name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.3.0-dev.4
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.1
  x509: ^0.2.4+2
  jose: ^0.3.4
  dotenv: ^4.2.0
  openid_client: ^0.4.8
  firebase_dart: ^1.1.4
  path: ^1.9.0
  meta: ^1.12.0
  http: ^1.2.1
  crypto_keys: ^0.3.0+1
  collection: ^1.18.0
  gcloud: ^0.8.12
  firebaseapis: ^0.2.0
  snapshot: ^0.2.5
  _discoveryapis_commons: ^1.0.6
  googleapis: ^12.0.0

dev_dependencies:
  test: ^1.17.8
  fake_async: ^1.2.0
  lints: ^2.0.0
  mockito: ^5.0.10

false_secrets:
 - /lib/src/testing.dart 